# agents/sub_agents/domain_base_agent.py
# Abstract base for all T2 domain agents.
#
# SCALING PATTERN:
#   To add a new domain agent (e.g. DASHBOARD):
#     1. Create dashboard_agent.py subclassing DomainBaseAgent
#     2. Set group_name = "DASHBOARD"
#     3. Set _template_model = DashboardQueryTemplate
#     4. Add YAML prompt at knowledge/prompts/sub_agents/dashboard.yaml
#     5. Register in agent_registry.py
#     Nothing in this file changes.

from __future__ import annotations

from abc import ABC, abstractmethod
from pathlib import Path
from typing import Optional, Type

from presentation.models.routing_decision import RoutingDecision
from presentation.models.query_template import QueryTemplate
from infrastructure.llm_sdk.gemini import GeminiClient
from utils.prompt_loader import load as load_prompt
from utils.llm_response_validator import validate, build_correction_prompt
from utils.logger import get_app_logger

logger = get_app_logger("agent.domain_base")

_PROMPTS_DIR = (
    Path(__file__).parent.parent.parent.parent
    / "knowledge" / "prompts" / "sub_agents"
)


class DomainBaseAgent(ABC):
    """
    Abstract base for all T2 domain agents.

    Each subclass must declare:
      group_name:      str                — e.g. "INSPECTION"
      _template_model: Type[QueryTemplate] — model to validate LLM output against

    The base class handles:
      - Prompt loading via prompt_loader (assembly_order respected)
      - LLM call via GeminiClient
      - Response validation via llm_response_validator
      - One retry with correction prompt on validation failure
    """

    group_name: str
    _template_model: Type[QueryTemplate] = QueryTemplate

    def __init__(self) -> None:
        self._llm = GeminiClient()
        self._system_prompt = load_prompt(
            _PROMPTS_DIR / f"{self.group_name.lower()}.yaml"
        )

    # ── Public ────────────────────────────────────────────────────────────────

    async def generate(
        self,
        routing: RoutingDecision,
        user_query: str,
        tenant_id: str,
        user_id: Optional[str],
    ) -> QueryTemplate:
        """
        Generates a QueryTemplate for the given routing decision.

        @param routing:    T1 RoutingDecision (primary group, scope hints).
        @param user_query: Original natural language query from the user.
        @param tenant_id:  Tenant UUID — injected into placeholders at runtime.
        @param user_id:    User UUID, or None for tenant-wide queries.
        @returns:          Validated QueryTemplate with placeholder pipeline.
        @raises RuntimeError: If LLM is unavailable or generation fails after retry.
        """
        if not self._llm.client:
            raise RuntimeError(
                f"LLM client is not configured for DomainAgent[{self.group_name}]."
            )

        user_msg = self._build_user_message(routing, user_query)
        raw = self._llm.generate_json(
            prompt=user_msg,
            system_instruction=self._system_prompt,
            agent=self.group_name,
        )

        try:
            template = validate(raw, self._template_model, user_query)
        except ValueError as exc:
            logger.warning(
                f"DomainAgent[{self.group_name}] generation failed (attempt 1): {exc}"
            )
            correction = build_correction_prompt(raw, self._template_model, user_query)
            raw_retry = self._llm.generate_json(
                prompt=correction,
                system_instruction=self._system_prompt,
                agent=self.group_name,
            )
            try:
                template = validate(raw_retry, self._template_model, user_query)
            except ValueError as exc2:
                logger.error(
                    f"DomainAgent[{self.group_name}] generation failed after retry: {exc2}"
                )
                raise RuntimeError(
                    f"Failed to generate QueryTemplate for [{self.group_name}]: {exc2}"
                ) from exc2

        logger.info(
            f"DomainAgent[{self.group_name}] generated template "
            f"(entity={template.entity_type})"
        )
        return template

    # ── Private ───────────────────────────────────────────────────────────────

    def _build_user_message(self, routing: RoutingDecision, user_query: str) -> str:
        """
        Formats the T2 user message with routing context.
        problem_description is the primary instruction — it is the clean
        intent statement generated by T1 specifically for this agent.
        """
        return (
            f"TASK: {routing.problem_description or user_query}\n"
            f"ORIGINAL QUERY: {user_query}\n"
            f"USER SCOPED: {'yes' if routing.user_scoped else 'no'}\n"
            f"ENTITY HINT: {routing.entity_hint or 'none'}\n"
            f"STATUS FILTER: {routing.status_filter or 'none'}\n"
            f"TIME WINDOW: "
            f"{routing.time_window.model_dump() if routing.time_window else 'none'}\n"
            f"COMPLEXITY: {routing.query_complexity}\n"
        )