# agents/sub_agents/inspection_group_agent.py
# InspectionGroupAgent: T2 domain agent for the unified INSPECTION group.
#
# Owns the full inspection lifecycle:
#   inspection · checklist · section · question · execution ·
#   responseHistory · inspectionObservation · task · taskObservation · report
#
# Version: v1.1

from application.agents.sub_agents.domain_base_agent import DomainBaseAgent
from presentation.models.query_template import InspectionQueryTemplate


class InspectionGroupAgent(DomainBaseAgent):
    """
    T2 domain agent responsible for generating MongoDB query templates
    for the INSPECTION domain group.

    The agent interprets routing instructions from the RootAgent and
    generates a validated InspectionQueryTemplate containing a MongoDB
    aggregation pipeline with runtime placeholders.

    Supported entities in this domain:

    Content Layer
    - checklist
    - section
    - question

    Assignment Layer
    - inspection

    Execution Layer
    - execution
    - responseHistory
    - inspectionObservation

    Resolution Layer
    - task
    - taskObservation

    Artifact Layer
    - report

    Critical behavioral rules (enforced via prompt):
    -----------------------------------------------
    • responseHistory queries MUST include the 3-stage deduplication block
      when calculating final responses.

    • execution does NOT contain assignedTo — user scope must always
      resolve through execution → inspection.

    • scheduleDate exists ONLY on inspection.

    • task.status is a direct string field — never lookup.

    • responseValues collection is explicitly excluded.

    Query templates generated by this agent are validated against
    InspectionQueryTemplate.
    """

    # Domain group name used by the orchestrator registry
    group_name = "INSPECTION"

    # Template model used for validating LLM output
    _template_model = InspectionQueryTemplate