# presentation/models/routing_decision.py
# Internal routing contract between T1 (RootAgent) and the orchestrator/T2 agents.
#
# RoutingPlan  = raw T1 LLM output     (validated from JSON)
# RoutingDecision = internal contract  (consumed by orchestrator + T2 agents)
#
# The split exists because:
#   - RoutingPlan owns the LLM output shape (changes when prompt changes)
#   - RoutingDecision owns the internal API  (changes when orchestrator changes)
#   - They evolve independently

from __future__ import annotations
from typing import Optional
from pydantic import BaseModel

from presentation.models.routing_plan import AgentGroup
from presentation.models.query_template import TimeWindow


class RoutingDecision(BaseModel):
    """
    Internal routing contract passed from RootAgent → Orchestrator → T2 agents.

    Produced by: root_agent._to_routing_decision()
    Consumed by: query_orchestrator._dispatch()
                 domain_base_agent._build_user_message()

    @param primary_group:        Domain agent that handles this query (T2 call).
    @param secondary_groups:     Additional agents if query spans domains.
    @param problem_description:  Plain-English intent scoped to the primary agent.
                                 Generated by T1, consumed by T2 as its instruction.
    @param query_complexity:     T1 assessment — 'simple' | 'complex'.
                                 Used by orchestrator for logging and future routing.
    @param user_scoped:          Whether results should be filtered by userId.
                                 Resolved by T2 from problem_description.
    @param entity_hint:          Specific entity type hint from T1 (optional).
    @param status_filter:        Status value to filter on (optional).
    @param time_window:          Time range constraint (optional).
    """
    primary_group: AgentGroup
    secondary_groups: list[AgentGroup] = []
    problem_description: str = ""
    query_complexity: str = "simple"

    # Scope hints — resolved by T2 agents from problem_description
    user_scoped: bool = False
    entity_hint: Optional[str] = None
    status_filter: Optional[str] = None
    time_window: Optional[TimeWindow] = None